### PR TITLE
Updates from master branch

### PR DESCRIPTION
**Pull request by smilesrg**
Please see https://github.com/davegardnerisme/nsqphp/issues/38

### CODE REVIEW

**Comment by smilesrg** [comment]
@rodrigueznicolas  @NoiseByNorthwest  @mhor  please update the library!

**Comment by NoiseByNorthwest** [comment]
@smilesrg done

**Comment by smilesrg** [comment]
@NoiseByNorthwest thank you so much!

**Comment by smilesrg** [comment]
@NoiseByNorthwest Please update the version at http://packagist.org

**Comment by NoiseByNorthwest** [comment]
@smilesrg done https://packagist.org/packages/socloz/nsqphp#dev-socloz

**Pull request merged**
